import { makeStyles, shorthands, tokens } from '@fluentui/react-components';
import { SUBITEM_CONNECTOR_COLOR } from '../supplier/purchaseOrderSubitemConnectorStyles';

export const RCCP_CAPACITY_ROW_HEIGHT = '34px';
export const RCCP_CAPACITY_CONTROL_WIDTH = '92px';

export const useRccpCapacityPlanningTableStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap(tokens.spacingVerticalS),
  },
  wrapper: {
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    maxHeight: '560px',
    overflow: 'auto',
    overflowX: 'auto',
    scrollbarGutter: 'stable',
  },
  table: {
    width: 'max-content',
    borderCollapse: 'separate',
    borderSpacing: 0,
    tableLayout: 'fixed',
  },
  headerCell: {
    backgroundColor: tokens.colorNeutralBackground2,
    position: 'sticky',
    top: 0,
    zIndex: 2,
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('8px', '10px'),
    textAlign: 'left',
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    whiteSpace: 'nowrap',
    verticalAlign: 'middle',
    ':hover [data-column-menu-trigger="true"]': {
      opacity: 1,
      pointerEvents: 'auto',
    },
    ':focus-within [data-column-menu-trigger="true"]': {
      opacity: 1,
      pointerEvents: 'auto',
    },
    ':has([data-column-menu-trigger-active="true"]) [data-column-menu-trigger="true"]': {
      opacity: 1,
      pointerEvents: 'auto',
    },
  },
  headerCellFiltered: {
    boxShadow: `inset 0 -3px 0 0 ${SUBITEM_CONNECTOR_COLOR}`,
  },
  headerCellContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    ...shorthands.gap('6px'),
  },
  headerCellLabel: {
    flex: '1 1 auto',
    minWidth: 0,
    overflow: 'hidden',
  },
  headerLabelText: {
    display: 'inline-block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '100%',
  },
  controlHeaderCell: {
    backgroundColor: tokens.colorNeutralBackground2,
    position: 'sticky',
    top: 0,
    left: 0,
    zIndex: 4,
    width: RCCP_CAPACITY_CONTROL_WIDTH,
    minWidth: RCCP_CAPACITY_CONTROL_WIDTH,
    maxWidth: RCCP_CAPACITY_CONTROL_WIDTH,
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('2px'),
    verticalAlign: 'middle',
  },
  controlCell: {
    position: 'sticky',
    left: 0,
    zIndex: 3,
    width: RCCP_CAPACITY_CONTROL_WIDTH,
    minWidth: RCCP_CAPACITY_CONTROL_WIDTH,
    maxWidth: RCCP_CAPACITY_CONTROL_WIDTH,
    height: RCCP_CAPACITY_ROW_HEIGHT,
    maxHeight: RCCP_CAPACITY_ROW_HEIGHT,
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('0', '2px'),
    boxSizing: 'border-box',
    verticalAlign: 'middle',
  },
  controlCellInner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    ...shorthands.padding('0', '4px'),
  },
  dataCell: {
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    ...shorthands.padding('0'),
    height: RCCP_CAPACITY_ROW_HEIGHT,
    maxHeight: RCCP_CAPACITY_ROW_HEIGHT,
    fontSize: tokens.fontSizeBase300,
    whiteSpace: 'nowrap',
    verticalAlign: 'middle',
    overflow: 'hidden',
  },
  cellInput: {
    display: 'block',
    width: '100%',
    maxWidth: '100%',
    height: RCCP_CAPACITY_ROW_HEIGHT,
    boxSizing: 'border-box',
    border: 'none',
    outline: 'none',
    backgroundColor: 'transparent',
    ...shorthands.padding('0', '10px'),
    fontSize: tokens.fontSizeBase300,
    fontFamily: 'inherit',
    color: tokens.colorNeutralForeground1,
    ':focus': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: tokens.colorBrandStroke1,
      outlineOffset: '-2px',
      backgroundColor: tokens.colorNeutralBackground1,
    },
  },
  alignRight: {
    textAlign: 'right',
    fontVariantNumeric: 'tabular-nums',
  },
  itemRow: {
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  rowDirty: {
    boxShadow: `inset 3px 0 0 0 ${tokens.colorPaletteMarigoldBorderActive}`,
  },
  rowNew: {
    boxShadow: `inset 3px 0 0 0 ${tokens.colorPaletteGreenBorderActive}`,
  },
  rowSelected: {
    backgroundColor: tokens.colorBrandBackground2,
  },
  rowBusy: { opacity: 0.65 },
  selectAll: { ...shorthands.padding('0') },
  rowCheckbox: { ...shorthands.padding('0') },
  empty: { color: tokens.colorNeutralForeground3 },
  error: { color: tokens.colorPaletteRedForeground1 },
});
