import React from 'react';
import { PopoverSurface } from '@fluentui/react-components';
import { FilterMenuMainPane, FilterMenuSubPane } from './PurchaseOrderColumnFilterMenuPanels';

export default function PurchaseOrderColumnFilterMenuPopoverContent({
  styles,
  column,
  columnTypeMeta,
  connectionTargets,
  isImageColumn,
  activeSubmenu,
  submenuTop,
  openSubmenu,
  canSetColumnTextStyle,
  canSetColumnFormatRules,
  canToggleWriteback,
  showWritebackLocked,
  handleToggleWriteback,
  writable,
  canAddColumn,
  canRenameColumn,
  handleRenameColumn,
  canEditFormulaColumn,
  handleEditFormulaColumn,
  canEditImageColumn,
  handleEditImageColumn,
  canRemoveColumn,
  handleRemoveColumn,
  canToggleLineTotal,
  isLineColumnSummed,
  handleToggleLineTotal,
  canPushLineTotalToHeader,
  handlePushLineTotalToHeader,
  canPushLineValuesToHeader,
  handlePushLineValuesToHeader,
  canMakeColumnSticky,
  isStickyColumn,
  canPromoteToSticky,
  canUnstickSticky,
  stickyColumnCount,
  handleMakeColumnSticky,
  setSortAsc,
  setSortDesc,
  clearSort,
  isDate,
  draft,
  operatorLabels,
  operatorEntries,
  handleOperatorSelect,
  handleValueChange,
  handleSecondaryValueChange,
  handleApply,
  handleClearFilter,
  handleAddType,
  remarksAlreadyAdded,
  textStyleDraft,
  handleTextColorChange,
  handleToggleBold,
  handleToggleItalic,
  handleToggleUnderline,
  handleApplyTextStyle,
  handleClearTextStyle,
  formatRulesDraft,
  formatReferenceColumns,
  handleApplyFormatRules,
  handleClearFormatRules,
  isGroupingColumn,
  groupingColor,
  onSetGroupingColumn,
  onClearGrouping,
  onSetGroupingColor,
  canToggleGroupSummary,
  isGroupSummaryColumn,
  handleToggleGroupSummary,
}) {
  return (
    <PopoverSurface className={styles.surface}>
      <FilterMenuMainPane
        styles={styles}
        columnLabel={column.label}
        columnTypeMeta={columnTypeMeta}
        connectionTargets={connectionTargets}
        showSortAndFilter={!isImageColumn}
        showGrouping={!isImageColumn}
        activeSubmenu={activeSubmenu}
        openSubmenu={openSubmenu}
        canSetColumnTextStyle={canSetColumnTextStyle}
        canSetColumnFormatRules={canSetColumnFormatRules && !isImageColumn}
        canToggleWriteback={canToggleWriteback}
        showWritebackLocked={showWritebackLocked}
        handleToggleWriteback={handleToggleWriteback}
        writable={writable}
        canAddColumn={canAddColumn}
        canRenameColumn={canRenameColumn}
        handleRenameColumn={handleRenameColumn}
        canEditFormulaColumn={canEditFormulaColumn}
        handleEditFormulaColumn={handleEditFormulaColumn}
        canEditImageColumn={canEditImageColumn}
        handleEditImageColumn={handleEditImageColumn}
        canRemoveColumn={canRemoveColumn}
        handleRemoveColumn={handleRemoveColumn}
        canToggleLineTotal={canToggleLineTotal}
        isLineColumnSummed={isLineColumnSummed}
        handleToggleLineTotal={handleToggleLineTotal}
        canPushLineTotalToHeader={canPushLineTotalToHeader}
        handlePushLineTotalToHeader={handlePushLineTotalToHeader}
        canPushLineValuesToHeader={canPushLineValuesToHeader}
        handlePushLineValuesToHeader={handlePushLineValuesToHeader}
        canMakeColumnSticky={canMakeColumnSticky}
        isStickyColumn={isStickyColumn}
        canPromoteToSticky={canPromoteToSticky}
        canUnstickSticky={canUnstickSticky}
        stickyColumnCount={stickyColumnCount}
        handleMakeColumnSticky={handleMakeColumnSticky}
        setSortAsc={setSortAsc}
        setSortDesc={setSortDesc}
        clearSort={clearSort}
        isDate={isDate}
        draft={draft}
        operatorLabels={operatorLabels}
        operatorEntries={operatorEntries}
        handleOperatorSelect={handleOperatorSelect}
        handleValueChange={handleValueChange}
        handleSecondaryValueChange={handleSecondaryValueChange}
        handleApply={handleApply}
        handleClearFilter={handleClearFilter}
      />
      <FilterMenuSubPane
        styles={styles}
        activeSubmenu={activeSubmenu}
        submenuTop={submenuTop}
        handleAddType={handleAddType}
        remarksAlreadyAdded={remarksAlreadyAdded}
        textStyleDraft={textStyleDraft}
        handleTextColorChange={handleTextColorChange}
        handleToggleBold={handleToggleBold}
        handleToggleItalic={handleToggleItalic}
        handleToggleUnderline={handleToggleUnderline}
        columnLabel={column.label}
        handleApplyTextStyle={handleApplyTextStyle}
        handleClearTextStyle={handleClearTextStyle}
        formatTarget={formatRulesDraft.formatTarget}
        setFormatTarget={formatRulesDraft.setFormatTarget}
        formatRules={formatRulesDraft.formatRules}
        formatReferenceColumns={formatReferenceColumns}
        addFormatRule={formatRulesDraft.addFormatRule}
        updateFormatRule={formatRulesDraft.updateFormatRule}
        removeFormatRule={formatRulesDraft.removeFormatRule}
        handleApplyFormatRules={handleApplyFormatRules}
        handleClearFormatRules={handleClearFormatRules}
        column={column}
        isGroupingColumn={isGroupingColumn}
        groupingColor={groupingColor}
        onSetGroupingColumn={onSetGroupingColumn}
        onClearGrouping={onClearGrouping}
        onSetGroupingColor={onSetGroupingColor}
        canToggleGroupSummary={canToggleGroupSummary}
        isGroupSummaryColumn={isGroupSummaryColumn}
        handleToggleGroupSummary={handleToggleGroupSummary}
      />
    </PopoverSurface>
  );
}
