import { makeStyles, shorthands, tokens } from '@fluentui/react-components';
import { SUBITEM_CONNECTOR_COLOR } from './purchaseOrderSubitemConnectorStyles';

export const usePurchaseOrderColumnFilterMenuStyles = makeStyles({
  trigger: {
    minWidth: '22px',
    width: '22px',
    height: '22px',
    ...shorthands.padding('0'),
    color: tokens.colorNeutralForeground3,
    cursor: 'pointer',
    flexShrink: 0,
    opacity: 0,
    pointerEvents: 'none',
    transitionDuration: '0.12s',
    transitionProperty: 'opacity,color,background-color',
    ':hover': {
      color: tokens.colorBrandForeground1,
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  triggerActive: {
    opacity: 1,
    pointerEvents: 'auto',
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1Hover,
    borderRadius: tokens.borderRadiusSmall,
    ':hover': {
      color: tokens.colorBrandForeground1,
      backgroundColor: tokens.colorNeutralBackground2,
    },
  },
  triggerFilterActive: {
    opacity: 1,
    pointerEvents: 'auto',
    color: tokens.colorNeutralForeground1,
    backgroundColor: SUBITEM_CONNECTOR_COLOR,
    borderRadius: tokens.borderRadiusSmall,
    boxShadow: `inset 0 0 0 1px ${SUBITEM_CONNECTOR_COLOR}`,
    ':hover': {
      color: tokens.colorNeutralForeground1,
      backgroundColor: SUBITEM_CONNECTOR_COLOR,
    },
  },
  surface: {
    ...shorthands.padding('0'),
    width: 'auto',
    maxWidth: 'none',
    boxSizing: 'border-box',
    display: 'block',
    position: 'relative',
    overflow: 'visible',
  },
  mainPane: {
    width: '256px',
    minWidth: '256px',
    boxSizing: 'border-box',
    ...shorthands.padding('6px', '8px'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('6px'),
    overflow: 'visible',
  },
  sectionTitle: {
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    marginTop: '2px',
  },
  sectionBlock: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('2px'),
  },
  subPane: {
    width: '240px',
    minWidth: '240px',
    boxSizing: 'border-box',
    ...shorthands.padding('8px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow16,
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
    left: 'calc(100% - 8px)',
    position: 'absolute',
    zIndex: 1,
  },
  subPaneTitle: {
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    marginBottom: '4px',
  },
  submenuButton: {
    justifyContent: 'space-between',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  submenuButtonActive: {
    backgroundColor: tokens.colorNeutralBackground1Selected,
  },
  sortActions: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('0'),
  },
  sortButton: {
    justifyContent: 'flex-start',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  menuItemContent: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    ...shorthands.gap('8px'),
    color: tokens.colorNeutralForeground1,
  },
  menuItemContentDisabled: {
    color: tokens.colorNeutralForegroundDisabled,
  },
  menuItemIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase300,
    lineHeight: 1,
    width: '16px',
    minWidth: '16px',
    flexShrink: 0,
  },
  menuItemIconDisabled: {
    color: tokens.colorNeutralForegroundDisabled,
  },
  submenuItemContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  submenuItemLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    ...shorthands.gap('8px'),
  },
  divider: {
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
  },
  fieldTitle: {
    fontWeight: tokens.fontWeightSemibold,
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shorthands.gap('8px'),
  },
  titleLabelWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    minWidth: 0,
    ...shorthands.gap('6px'),
  },
  titleLabelButton: {
    minWidth: 'auto',
    height: 'auto',
    ...shorthands.padding('0'),
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusSmall,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  titleLockIcon: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase300,
    width: '16px',
    minWidth: '16px',
    lineHeight: 1,
    flexShrink: 0,
  },
  typeMeta: {
    display: 'inline-flex',
    alignItems: 'center',
    ...shorthands.gap('4px'),
  },
  typeMetaConnectionButton: {
    minWidth: '16px',
    width: '16px',
    height: '16px',
    ...shorthands.padding('0'),
    color: tokens.colorBrandForeground1,
  },
  typeMetaConnectionButtonActive: {
    backgroundColor: tokens.colorNeutralBackground1Selected,
  },
  typeMetaConnectionList: {
    margin: 0,
    paddingLeft: '16px',
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  inlineConnectionList: {
    margin: 0,
    paddingLeft: '16px',
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  d365SyncLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    ...shorthands.gap('6px'),
  },
  d365SyncIcon: {
    width: '14px',
    height: '14px',
    objectFit: 'contain',
  },
  displayModeButtonSelected: {
    backgroundColor: tokens.colorNeutralBackground1Selected,
    boxShadow: `inset 0 0 0 1px ${tokens.colorBrandStroke1}`,
  },
  typeIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    lineHeight: 1,
  },
  typeText: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
  },
  filterBlock: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
  },
  filterSectionLabel: {
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  filterValueStack: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    ...shorthands.gap('2px'),
    width: '100%',
    minWidth: 0,
  },
  filterOperatorWrap: {
    position: 'relative',
    flexShrink: 0,
  },
  filterOperatorLink: {
    minWidth: 'auto',
    height: 'auto',
    ...shorthands.padding('0'),
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightRegular,
    justifyContent: 'flex-start',
    ':hover': {
      color: tokens.colorBrandForeground1,
      textDecorationLine: 'underline',
    },
    ':active': {
      color: tokens.colorBrandForeground1,
    },
  },
  filterOperatorLinkContent: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    ...shorthands.gap('4px'),
  },
  filterOperatorChevron: {
    fontSize: tokens.fontSizeBase300,
    lineHeight: 1,
    flexShrink: 0,
  },
  filterOperatorFlyout: {
    position: 'absolute',
    top: '0',
    left: 'calc(100% + 4px)',
    zIndex: 2,
    minWidth: '168px',
    boxSizing: 'border-box',
    ...shorthands.padding('4px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow8,
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('0'),
  },
  filterOperatorOption: {
    justifyContent: 'flex-start',
    minWidth: 'auto',
    width: '100%',
    height: '28px',
    ...shorthands.padding('0', '8px'),
    color: tokens.colorNeutralForeground1,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  filterValueField: {
    flexGrow: 1,
    minWidth: 0,
    width: '100%',
  },
  filterBetweenRow: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('6px'),
  },
  filterValueFieldBetween: {
    flex: '1 1 0',
    minWidth: 0,
  },
  filterClearButton: {
    flex: '0 0 auto',
    minWidth: 'auto',
    height: '24px',
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    ...shorthands.padding('0', '6px'),
  },
  filterApplyButton: {
    flex: '0 0 auto',
    minWidth: 'auto',
    height: '24px',
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    ...shorthands.padding('0', '6px'),
  },
  filterActionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    ...shorthands.gap('6px'),
    width: '100%',
    marginTop: '2px',
  },
  filterHint: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase200,
  },
  colorFilterSwatches: {
    display: 'flex',
    flexWrap: 'wrap',
    ...shorthands.gap('6px'),
    width: '100%',
  },
  colorFilterSwatch: {
    width: '22px',
    height: '22px',
    ...shorthands.padding('0'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusSmall,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  colorFilterSwatchActive: {
    ...shorthands.borderColor(tokens.colorNeutralForeground1),
    boxShadow: `inset 0 0 0 2px ${tokens.colorNeutralBackground1}, 0 0 0 1px ${tokens.colorNeutralForeground1}`,
  },
  colorFilterNoColorSwatch: {
    backgroundColor: tokens.colorNeutralBackground1,
    backgroundImage: `linear-gradient(to top left, transparent calc(50% - 1px), ${tokens.colorPaletteRedForeground1} calc(50% - 1px), ${tokens.colorPaletteRedForeground1} calc(50% + 1px), transparent calc(50% + 1px))`,
  },
  filterRow: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
  },
  actionRow: {
    display: 'flex',
    ...shorthands.gap('6px'),
  },
  subPaneFullWidthButton: {
    width: '100%',
    justifyContent: 'flex-start',
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  hint: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
  },
  colorInput: {
    width: '40px',
    height: '28px',
    ...shorthands.padding('0'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusSmall,
  },
  colorRow: {
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('8px'),
  },
  formatButtons: {
    display: 'flex',
    ...shorthands.gap('4px'),
  },
  formatButton: {
    minWidth: '32px',
    width: '32px',
    ...shorthands.padding('0'),
  },
  stylePreview: {
    ...shorthands.padding('4px', '6px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusSmall,
  },
  groupingSection: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('8px'),
  },
  groupingToggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shorthands.gap('8px'),
  },
  groupingColorField: {
    ...shorthands.gap('4px'),
  },
});
